// Code generated by Kitex v0.9.1. DO NOT EDIT.

package urlservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	url "shorturl/kitex_gen/short/url"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	AddUrl(ctx context.Context, req *url.UrlRequest, callOptions ...callopt.Option) (r *url.UrlResponse, err error)
	Update(ctx context.Context, req *url.UrlRequest, callOptions ...callopt.Option) (r *url.UrlResponse, err error)
	Delete(ctx context.Context, req *url.UrlRequest, callOptions ...callopt.Option) (r *url.UrlResponse, err error)
	Sreach(ctx context.Context, req *url.UrlRequest, callOptions ...callopt.Option) (r *url.UrlResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kUrlServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUrlServiceClient struct {
	*kClient
}

func (p *kUrlServiceClient) AddUrl(ctx context.Context, req *url.UrlRequest, callOptions ...callopt.Option) (r *url.UrlResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddUrl(ctx, req)
}

func (p *kUrlServiceClient) Update(ctx context.Context, req *url.UrlRequest, callOptions ...callopt.Option) (r *url.UrlResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Update(ctx, req)
}

func (p *kUrlServiceClient) Delete(ctx context.Context, req *url.UrlRequest, callOptions ...callopt.Option) (r *url.UrlResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Delete(ctx, req)
}

func (p *kUrlServiceClient) Sreach(ctx context.Context, req *url.UrlRequest, callOptions ...callopt.Option) (r *url.UrlResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Sreach(ctx, req)
}
